trigger:
  - master

variables:
  - group: pay-as-you-go-subscription

pool:
  vmImage: "windows-latest"

steps:
  - task: CacheBeta@1
    inputs:
      key: 'npm | "$(Agent.OS)" | package-lock.json'
      path: $(Pipeline.Workspace)/.npm
      restoreKeys: 'npm | "$(Agent.OS)"'

  - script: npm ci

  - script: |
      npm run build
    displayName: "build"

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'Pay-As-You-Go (ef7fec7f-59c8-46f3-8fd6-b66cbd0a1205)'
      scriptType: "ps"
      scriptLocation: "inlineScript"
      inlineScript: az storage blob upload-batch --account-name $(blog-storage-account) --account-key $(blog-storage-key) -s ./build/. -d '$web/product/trivia'
